"""Which generated tests still describe the endpoint they were written for.

A test is only trustworthy while the handler it was written against is unchanged.
This compares what each test verified (`verified_at_commit`, the *handler line's*
commit) with what that handler is now, and says why when they differ.
"""

from __future__ import annotations

from pathlib import Path

from contextgit.core.models import Endpoint, EndpointGraph, EndpointTestSuite

_MISSING = "This endpoint is no longer in the project — its tests are retired."


def _reason(endpoint: Endpoint, commit: str) -> str:
    """A short sentence naming the change that moved the endpoint under its tests."""
    parts = [f"The handler changed in {commit[:7]}"]
    provenance = endpoint.provenance
    if provenance is not None:
        if provenance.code_commit_summary:
            parts.append(f"“{provenance.code_commit_summary}”")
        if provenance.tracked and provenance.run_name:
            parts.append(f"(run “{provenance.run_name}”)")
    parts.append("— re-run the tests to confirm the new behaviour.")
    return " ".join(parts)


def annotate(
    project: Path | str, suite: EndpointTestSuite, graph: EndpointGraph
) -> EndpointTestSuite:
    """Mark every entry fresh / stale / retired, with the reason attached."""
    known = {endpoint.id: endpoint for endpoint in graph.endpoints}
    fresh = stale = retired = 0

    for entry in suite.files:
        if not entry.endpoint_id:
            # Found on disk but not generated by us: nothing to compare against.
            entry.state = "untested"
            entry.reason = None
            continue

        endpoint = known.get(entry.endpoint_id)
        if endpoint is None:
            entry.state = "retired"
            entry.reason = _MISSING
            retired += 1
            continue

        current = endpoint.provenance.code_commit if endpoint.provenance else None
        verified = entry.verified_at_commit
        if verified is None or current is None:
            # Never ran, or the project is not a git repo: we cannot judge.
            entry.state = "untested"
            entry.reason = None
        elif current != verified:
            entry.state = "stale"
            entry.reason = _reason(endpoint, current)
            stale += 1
        else:
            entry.state = "fresh"
            entry.reason = None
            fresh += 1

    suite.project_path = str(project)
    suite.stale = stale
    suite.retired = retired
    return suite
