"""Hashing spec tests.

The fixtures below were generated with Node using the exact canonicalization
from the landing page demo (lib/landing.ts). If any of these tests fail, our
Python hashing has drifted from the user-visible spec.
"""

import hashlib
import json

from hypothesis import given, settings
from hypothesis import strategies as st

from contextgit.core.hashing import canonical_json, commit_id, content_commit_id

# (message, canonical_string, expected_hash) — generated by Node
FIXTURES = [
    (
        "Spec the limit: 100 requests per minute per API key.",
        '{"messages":[{"content":"Spec the limit: 100 requests per minute per API key.","role":"user"}],'
        '"metadata":{"kind":"normal","model":"example-model"},"parent_ids":["a3f9c21"]}',
        "0e11298972c247e4740fe0c20a71e4da7fcbce1146fcd6579637fc7b04e151f6",
    ),
    (
        "héllo wörld ünïcode ✓",
        '{"messages":[{"content":"héllo wörld ünïcode ✓","role":"user"}],'
        '"metadata":{"kind":"normal","model":"example-model"},"parent_ids":["a3f9c21"]}',
        "24ab98a7edbd3f1406180018b68c3338d406a7361814b86d3738cb627fd67d4f",
    ),
    (
        "line1\nline2\ttab",
        '{"messages":[{"content":"line1\\nline2\\ttab","role":"user"}],'
        '"metadata":{"kind":"normal","model":"example-model"},"parent_ids":["a3f9c21"]}',
        "9f2a22a0b741df2825341c236dcd35fdb96f44d4f85a82cd1e28e9be5e05b703",
    ),
    (
        'quote" and backslash\\ plus emoji 🌿',
        '{"messages":[{"content":"quote\\" and backslash\\\\ plus emoji 🌿","role":"user"}],'
        '"metadata":{"kind":"normal","model":"example-model"},"parent_ids":["a3f9c21"]}',
        "6104d014e184f20491fcaa12f28ed537467f445d6716a7be4ceabb6b362d8d9c",
    ),
]


class TestLandingPageSpec:
    """The landing page demo is the spec; Python must match it byte for byte."""

    def test_demo_message_matches_js(self) -> None:
        content, canon, expected = FIXTURES[0]
        model = "example-model"
        got = content_commit_id(content, model=model)
        assert got == expected
        # and the canonical string itself matches
        payload = (
            '{"messages":[{"content":' + json.dumps(content, ensure_ascii=False) + ',"role":"user"}],'
            '"metadata":{"kind":"normal","model":' + json.dumps(model) + '},"parent_ids":["a3f9c21"]}'
        )
        assert payload == canon

    def test_unicode_content_is_literal_not_escaped(self) -> None:
        _, _, expected = FIXTURES[1]
        assert content_commit_id("héllo wörld ünïcode ✓", model="example-model") == expected

    def test_control_chars_escaped_like_json_stringify(self) -> None:
        _, _, expected = FIXTURES[2]
        assert content_commit_id("line1\nline2\ttab", model="example-model") == expected

    def test_quotes_and_backslashes(self) -> None:
        _, _, expected = FIXTURES[3]
        assert content_commit_id('quote" and backslash\\ plus emoji 🌿', model="example-model") == expected

    def test_hash_is_lowercase_hex_sha256(self) -> None:
        cid = content_commit_id("anything", model="m")
        assert len(cid) == 64
        assert cid == cid.lower()
        int(cid, 16)  # parses as hex


class TestDeterminism:
    """Data-model rules: same input -> same id; any change -> different id."""

    def test_same_input_same_id(self) -> None:
        kwargs = dict(parent_ids=["a"], messages=[("user", "hi")], kind="normal", model="m")
        assert commit_id(**kwargs) == commit_id(**kwargs)

    def test_parent_order_matters(self) -> None:
        a = commit_id(parent_ids=["p1", "p2"], messages=[("user", "hi")], kind="merge", model="m")
        b = commit_id(parent_ids=["p2", "p1"], messages=[("user", "hi")], kind="merge", model="m")
        assert a != b

    def test_kind_and_model_matter(self) -> None:
        base = dict(parent_ids=["p"], messages=[("user", "hi")], model="m")
        assert commit_id(kind="normal", **base) != commit_id(kind="note", **base)
        assert commit_id(kind="normal", model="m1", **{k: v for k, v in base.items() if k != "model"}) != commit_id(
            kind="normal", model="m2", **{k: v for k, v in base.items() if k != "model"}
        )

    @settings(max_examples=200, deadline=None)
    @given(
        content=st.text(min_size=0, max_size=300),
        parent=st.text(min_size=1, max_size=64, alphabet="0123456789abcdef"),
    )
    def test_property_deterministic_and_length(self, content: str, parent: str) -> None:
        a = commit_id(parent_ids=[parent], messages=[("user", content)], kind="normal", model="m")
        b = commit_id(parent_ids=[parent], messages=[("user", content)], kind="normal", model="m")
        assert a == b
        assert len(a) == 64


class TestCanonicalJson:
    def test_sorted_keys_no_whitespace(self) -> None:
        obj = {"b": 1, "a": {"d": 2, "c": 3}}
        assert canonical_json(obj) == '{"a":{"c":3,"d":2},"b":1}'

    def test_unicode_literal(self) -> None:
        assert canonical_json({"k": "é"}) == '{"k":"é"}'

    def test_matches_manual_sha256(self) -> None:
        expected = hashlib.sha256(
            b'{"messages":[],"metadata":{"kind":"normal","model":"m"},"parent_ids":["x"]}'
        ).hexdigest()
        assert commit_id(parent_ids=["x"], messages=[], kind="normal", model="m") == expected
