import type { PlaygroundItem, PlaygroundKind } from "./playground";

function guided(
  id: string, label: string, kind: PlaygroundKind, vendor: string,
  summary: string, capabilities: string[], docsUrl: string, reason: string,
  setup?: string[],
): PlaygroundItem {
  return { id, label, kind, vendor, summary, capabilities, docsUrl, trust: "community", install: { kind: "docs", reason }, setup };
}

/** Maintainer docs and npm metadata checked 2026-10-08. Auth never goes in catalog data. */
export const ECOSYSTEM_ITEMS: PlaygroundItem[] = [
  {
    id: "filesystem", label: "Filesystem", kind: "mcp", vendor: "Model Context Protocol",
    summary: "Let agents search and read files inside this project. Warden blocks writes and access outside the granted workspace.",
    trust: "community", capabilities: ["Files", "Code search", "Project read access"],
    docsUrl: "https://github.com/modelcontextprotocol/servers/tree/main/src/filesystem",
    install: { kind: "npm", pkg: "@modelcontextprotocol/server-filesystem", version: "2026.8.31", bin: "dist/index.js" },
    sandbox: { projectRead: true, args: ["{project}"] },
    tryTools: ["list_allowed_directories", "list_directory", "read_text_file", "search_files"],
    tryExamples: { list_directory: { path: "{project}" }, read_text_file: { path: "{project}/README.md", head: 30 }, search_files: { path: "{project}", pattern: "*.ts" } },
  },
  {
    id: "memory", label: "Knowledge Graph Memory", kind: "mcp", vendor: "Model Context Protocol",
    summary: "Keep entities, relationships and observations in a local knowledge graph with a dedicated project memory directory.",
    trust: "community", capabilities: ["Memory", "Knowledge graph", "Local persistence"],
    docsUrl: "https://github.com/modelcontextprotocol/servers/tree/main/src/memory",
    install: { kind: "npm", pkg: "@modelcontextprotocol/server-memory", version: "2026.8.31", bin: "dist/index.js" },
    sandbox: { writeDirectory: ".contextgit-playground/memory", env: { MEMORY_FILE_PATH: "{state}/memory.jsonl" } },
    tryTools: ["read_graph", "search_nodes", "open_nodes"],
    tryExamples: { search_nodes: { query: "architecture" }, open_nodes: { names: ["ContextGit"] } },
    tryNote: "Try only reads the graph. Connected agents can write to its dedicated memory directory.",
  },
  {
    id: "sequential-thinking", label: "Sequential Thinking", kind: "mcp", vendor: "Model Context Protocol",
    summary: "Give an agent a structured scratchpad for multi-step reasoning, revisions and branching thoughts.",
    trust: "community", capabilities: ["Reasoning", "Planning", "Thought revisions"],
    docsUrl: "https://github.com/modelcontextprotocol/servers/tree/main/src/sequentialthinking",
    install: { kind: "npm", pkg: "@modelcontextprotocol/server-sequential-thinking", version: "2026.8.31", bin: "dist/index.js" },
    sandbox: {},
  },
  {
    id: "context7", label: "Context7", kind: "mcp", vendor: "Upstash",
    summary: "Look up current library documentation and version-specific examples while writing code.",
    trust: "community", capabilities: ["Documentation", "Library search", "Version-aware examples"],
    docsUrl: "https://github.com/upstash/context7",
    install: { kind: "npm", pkg: "@upstash/context7-mcp", version: "4.2.0", bin: "dist/index.js" },
    sandbox: { network: ["context7.com"] },
    tryTools: ["resolve-library-id", "query-docs"],
    tryExamples: { "resolve-library-id": { libraryName: "react", query: "How to clean up useEffect?" }, "query-docs": { libraryId: "/websites/react_dev", query: "useEffect cleanup examples" } },
    tryNote: "Your query is sent to Context7. This setup forwards no API keys; anonymous access is subject to provider limits.",
  },
  guided("github-mcp", "GitHub", "mcp", "GitHub", "Search repositories, inspect pull requests and work with issues through GitHub's maintained MCP server.", ["Repositories", "Pull requests", "Issues"], "https://github.com/github/github-mcp-server", "Use GitHub's hosted server with your MCP client's OAuth flow. Start with read-only toolsets and review repository access.", ["Choose the hosted server in the official setup guide.", "Authenticate in your MCP client and limit access to the repositories you need.", "Enable read-only mode before adding write toolsets."]),
  guided("playwright-mcp", "Playwright", "mcp", "Microsoft", "Drive browser tests using page accessibility snapshots, screenshots and deterministic browser actions.", ["Browser testing", "Accessibility", "Screenshots"], "https://github.com/microsoft/playwright-mcp", "Browser binaries, session isolation and network access need a dedicated policy. Follow Microsoft's setup guide; this entry does not auto-launch a browser.", ["Install @playwright/mcp through your MCP client using the documented command.", "Use an isolated browser profile and grant only the required sites.", "Review the server's security guidance before handling authenticated sessions."]),
  guided("chrome-devtools", "Chrome DevTools", "mcp", "Chrome DevTools", "Inspect browser performance, network requests and console output while debugging frontend code.", ["Performance", "Browser debugging", "Network inspection"], "https://github.com/ChromeDevTools/chrome-devtools-mcp", "Connect with a dedicated Chrome profile. Review browser-session access and telemetry settings in the maintainer's guide."),
  guided("serena", "Serena", "mcp", "Oraios", "Navigate symbols, references and code structure with language-server-backed code intelligence.", ["Code intelligence", "Symbol search", "Refactoring"], "https://github.com/oraios/serena", "Follow Serena's own quick start. Its maintainers advise against marketplace install recipes; language-server setup and editing permissions need project-specific review."),
  guided("firecrawl", "Firecrawl", "mcp", "Firecrawl", "Search the web and extract structured content from documentation and research pages.", ["Web search", "Scraping", "Documentation research"], "https://github.com/firecrawl/firecrawl-mcp-server", "Configure Firecrawl in your MCP client with a provider API key. Review quota, billing and destination access; Playground does not save keys."),
  guided("sentry", "Sentry", "mcp", "Sentry", "Bring application errors, issue context and debugging evidence into your development workflow.", ["Error investigation", "Observability", "Debugging"], "https://github.com/getsentry/sentry-mcp", "Connect using Sentry's documented authentication flow and scope it to the organizations and projects you need."),
  guided("linear", "Linear", "mcp", "Linear", "Search project issues and planning context from the team's Linear workspace.", ["Issues", "Project planning", "Team context"], "https://linear.app/docs/mcp", "Connect Linear's hosted MCP server through your client's OAuth flow. Review workspace access before enabling issue mutations."),
  guided("supabase", "Supabase", "mcp", "Supabase", "Inspect development database schema, logs and project context through Supabase's MCP server.", ["Database", "Schema inspection", "Development projects"], "https://supabase.com/docs/guides/ai-tools/mcp", "Use a development project, select one project and enable read-only mode. Complete provider authentication in your MCP client."),
  guided("uv", "uv", "tool", "Astral", "Manage Python packages, virtual environments and one-shot tools with a fast Python toolchain.", ["Python", "Package management", "Virtual environments"], "https://docs.astral.sh/uv/getting-started/installation/", "Choose the installation method for your operating system from Astral's guide. Native toolchain setup is managed outside Playground."),
  guided("ripgrep", "ripgrep", "tool", "BurntSushi", "Search source code quickly with regular expressions and gitignore-aware directory traversal.", ["Code search", "Regex", "Local CLI"], "https://github.com/BurntSushi/ripgrep", "Install the native rg binary with your operating system's package manager or a maintainer release."),
  {
    id: "biome", label: "Biome", kind: "tool", vendor: "Biome", trust: "community",
    summary: "Format and lint JavaScript, TypeScript, JSON and other supported project files.",
    capabilities: ["Formatting", "Linting", "JavaScript / TypeScript"], docsUrl: "https://biomejs.dev/installation/quick-start/",
    install: { kind: "npm", pkg: "@biomejs/biome", version: "2.5.15", bin: "bin/biome" },
    tryTools: ["help"], tryCommand: "biome --help",
    tryNote: "Try shows available commands. Formatting and lint fixes are run explicitly through the CLI.",
  },
  {
    id: "smithery", label: "Smithery CLI", kind: "tool", vendor: "Smithery", trust: "community",
    summary: "Discover MCP integrations and manage service connections from a command-line workflow.",
    capabilities: ["MCP discovery", "Connections", "CLI"], docsUrl: "https://smithery.ai/docs/concepts/cli",
    install: { kind: "npm", pkg: "@smithery/cli", version: "4.11.1", bin: "dist/index.js" },
    tryTools: ["help"], tryCommand: "smithery --help",
    tryNote: "Try shows CLI help. Authentication, connections and further installs require explicit CLI actions.",
  },
  guided("agent-scan", "Snyk Agent Scan", "tool", "Snyk", "Inspect agent components, MCP servers and skills for prompt injection and other security risks.", ["Security scanning", "MCP audit", "Skill inspection"], "https://github.com/snyk/agent-scan", "The scanner requires Snyk credentials and can execute configured servers. Review consent and run untrusted scans inside a disposable sandbox."),
  ...[
    ["frontend-design", "Frontend Design", "Design", "Build distinctive interfaces with a reusable frontend design workflow."],
    ["code-review", "Code Review", "Pull requests", "Review pull requests with specialized review agents and confidence scoring."],
    ["feature-dev", "Feature Development", "Architecture", "Explore a codebase, plan architecture and review implementation through a guided feature workflow."],
    ["plugin-dev", "Plugin Development", "Plugin authoring", "Author and validate Claude Code plugins, commands, hooks and MCP integrations."],
    ["security-guidance", "Security Guidance", "Security review", "Add security checks and review guidance around generated code and changes."],
    ["typescript-lsp", "TypeScript LSP", "Code intelligence", "Add JavaScript and TypeScript language-server intelligence to Claude Code."],
    ["pyright-lsp", "Pyright LSP", "Python", "Add Python type checking and language-server intelligence to Claude Code."],
  ].map(([id, label, capability, summary]) => guided(`plugin-${id}`, label, "plugin", "Anthropic", summary, ["Claude Code", capability], `https://github.com/anthropics/claude-plugins-official/tree/main/plugins/${id}`, "Install through Claude Code's official marketplace. Review the plugin's skills, agents, hooks and prerequisites before enabling it.", [`claude plugin install ${id}@claude-plugins-official --scope project`, "Restart Claude Code and inspect the plugin's declared components."])),
  guided("plugin-superpowers", "Superpowers", "plugin", "Obra", "Add structured brainstorming, debugging, test-driven development and implementation workflows to an agent.", ["Claude Code", "TDD", "Development workflows"], "https://github.com/obra/superpowers", "Follow the maintainer's install instructions for your client. This workflow can introduce agents and hooks; review them before enabling it.", ["claude plugin install superpowers@claude-plugins-official --scope project", "Read the maintainer's instructions for other supported clients."]),
];
